names=['kang','zhi','yuan','shuai','ge']
poped_name=names.pop(2)
print(poped_name)
print(names)
names.insert(2,'yuan')
names.insert(3,'bu')
names.insert(4,'shi')
names.append(' 哦')
print(names)
print(names[0])
